# # Simple workflow for deploying static content to GitHub Pages
# name: Deploy Vite to GitHub Pages

# on:
#   # Runs on pushes targeting the default branch
#   push:
#     branches: ["dev"]

#   # Runs on pull requests targeting the dev branch
#   pull_request:
#     branches: ["dev"]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # Allow one concurrent deployment
# concurrency:
#   group: "pages"
#   cancel-in-progress: true

# jobs:
#   # Single deploy job since we're just deploying
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v5
#       - name: Set up Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#           cache: "npm"
#       - name: Install dependencies
#         run: npm ci
#       - name: Build
#         run: npm run build
#       - name: Setup Pages
#         uses: actions/configure-pages@v5
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v4
#         with:
#           # Upload dist folder
#           path: "./dist"
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4

# Workflow for building and deploying Vite app to GitHub Pages
name: Build and Deploy Vite to GitHub Pages

on:
  # Runs on pushes targeting the dev branch
  push:
    branches: ["dev"]

  # Runs on pull requests targeting the dev branch
  pull_request:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: ./dist

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/dev'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
